In [ ]:
# A library is a corpus of reusable code modules and their accompanying documentation. Libraries are bundled into packages that
# you install, which can then be imported into your coding environment as needed. You’ll typically encounter the terms “library” 
# and “package” used interchangeably. Generally, this certificate program will refer to both as libraries, but it’s important to 
# be acquainted with both terms.

# Modules are similar to libraries, in that they are groups of related classes and functions, but they are generally 
# subcomponents of libraries. In other words, a library can have many different modules, and you can choose to import the entire
# library or just the module you need. 

# NumPy arrays are mutable. However, array cannot be lengthened or shortened.

In [1]:
list1=[1,2,3]
list2=[4,5,6]

list1 * list2

TypeError: can't multiply sequence by non-int of type 'list'

In [2]:
import numpy as np

array1=np.array(list1)
array2=np.array(list2)

array1 * array2

array([ 4, 10, 18])

In [5]:
from numpy import array

array1=array(list1)
array2=array(list2)

array1 * array2

array([ 4, 10, 18])

In [11]:
arr = array([1, 2, "coconut"])
arr                   # arrayler tüm değişkenleri aynı veri tipinde olmaya zorlar, 1 ve 2 de string bu yüzden.

array(['1', '2', 'coconut'], dtype='<U21')

In [12]:
arr = array([1, 2, 3])
arr.dtype

dtype('int64')

In [38]:
array2d = array([[1, 2], [3, 4], [5, 6], [7, 8]])

print("Matrix shape: {}".format(array2d.shape))
print("Matrix dimension: {}".format(array2d.ndim))
print("Matrix size: {}".format(array2d.size))
print("Matrix transpoze: {}".format(array2d.T))

array2d

Matrix shape: (4, 2)
Matrix dimension: 2
Matrix size: 8
Matrix transpoze: [[1 3 5 7]
 [2 4 6 8]]


array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [31]:
array2d = array2d.reshape(8, 1)
print(array2d)

array2d = array2d.reshape(4, -1)
array2d

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [22]:
arr_3d = np.array([[[1, 2, 3],
                    [3, 4, 5]],

                   [[5, 6, 7],
                    [7, 8, 9]]])

print(arr_3d. shape) 
print(arr_3d.ndim)
arr_3d

(2, 2, 3)
3


array([[[1, 2, 3],
        [3, 4, 5]],

       [[5, 6, 7],
        [7, 8, 9]]])

In [27]:
x = np.zeros((3, 2))
y = np.ones((2, 2))
z = np.full((5, 3), 8)

print(x)
print("\n")
print(y)
print("\n")
print(z)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


[[1. 1.]
 [1. 1.]]


[[8 8 8]
 [8 8 8]
 [8 8 8]
 [8 8 8]
 [8 8 8]]


In [28]:
array_2d = np.array([(1, 2, 3), (4, 5, 6)])
print(array_2d)
print()
array_2d.flatten()

[[1 2 3]
 [4 5 6]]



array([1, 2, 3, 4, 5, 6])

In [29]:
array_2d = np.array([(1, 2, 3), (4, 5, 6)])
print(array_2d)
print()
array_2d.tolist()

[[1 2 3]
 [4 5 6]]



[[1, 2, 3], [4, 5, 6]]

In [43]:
a = np.array([(1, 2, 3), (4, 5, 6)])
print(a)
print()

print(a[1])
print(a[0, 1])
print(a[1, 2])
a[:, 1:]

[[1 2 3]
 [4 5 6]]

[4 5 6]
2
6


array([[2, 3],
       [5, 6]])

In [ ]:
new_team = {}
for name, age, position in team:
    if position in new team:
        new team[position].append((name, age)) 
    else:
        new team[position] = [(name, age)]

new team             # Dictionary olabilir, yeniden bak